create table if not exists public.solutions (
  id text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.solution_history (
  id bigint generated by default as identity primary key,
  solution_id text not null,
  action text not null,
  actor text not null default 'anon',
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.solutions enable row level security;
alter table public.solution_history enable row level security;

drop policy if exists "solutions_select" on public.solutions;
drop policy if exists "solutions_insert" on public.solutions;
drop policy if exists "solutions_update" on public.solutions;
drop policy if exists "solutions_delete" on public.solutions;
drop policy if exists "solution_history_select" on public.solution_history;
drop policy if exists "solution_history_insert" on public.solution_history;

create policy "solutions_select"
on public.solutions
for select
to anon, authenticated
using (true);

create policy "solutions_insert"
on public.solutions
for insert
to anon, authenticated
with check (true);

create policy "solutions_update"
on public.solutions
for update
to anon, authenticated
using (true)
with check (true);

create policy "solutions_delete"
on public.solutions
for delete
to anon, authenticated
using (true);

create policy "solution_history_select"
on public.solution_history
for select
to anon, authenticated
using (true);

create policy "solution_history_insert"
on public.solution_history
for insert
to anon, authenticated
with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.solutions to anon, authenticated;
grant select, insert on public.solution_history to anon, authenticated;
grant usage, select on sequence public.solution_history_id_seq to anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_solutions_updated_at on public.solutions;

create trigger set_solutions_updated_at
before update on public.solutions
for each row
execute function public.set_updated_at();
